const myData = [
  {
    description: ' Mobile Plan',
    name: 'Mobile',
    role: 'user',
    resolution: '480p',
    number_of_devices: 5,
    devices: ['phone', 'tablet'],
    id: 1,
    videoQuality: 'Good',
    price: '20',
    portability: true,
  },
  {
    description: ' Standard Plan',
    name: 'Standard',
    role: 'user',
    resolution: '720p',
    number_of_devices: 5,
    devices: ['phone', 'tablet', 'computer', 'tv'],
    id: 2,
    videoQuality: 'Good',
    price: '20',
    portability: true,
  },
  {
    description: ' Premium Plan',
    name: 'Premium',
    role: 'user',
    resolution: '1080p',
    number_of_devices: 5,
    devices: ['phone', 'tablet', 'computer', 'tv'],
    id: 3,
    videoQuality: 'Better',
    price: '60',
    portability: true,
  },
  {
    description: ' Basic Plan',
    name: 'Basic',
    role: 'user',
    resolution: '4K+HDR',
    number_of_devices: 5,
    devices: ['phone', 'tablet', 'computer', 'tv'],
    id: 4,
    videoQuality: 'Best',
    price: '120',
    portability: true,
  },
];

export default myData;
